---

- include_vars: vars.yaml
- include: tasks/prereq.yaml
- include: tasks/rollback.yaml
  tags: ['never','rollback']

- name: Create install directory (if not exists)
  file:
          path: "{{ download_path }}"
          owner: "{{ owner }}"
          group: "{{ group }}"
          state: directory

- name: Fetch terraform file for Linux x86_64
  get_url:
          url: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
          dest: "{{ download_path }}"

- name: Extract zip file
  unarchive:
          src: /home/aorfanos/terraform/terraform_0.11.11_linux_amd64.zip
          dest: "{{ download_path }}"

- name: Remove zip file
  file:
          path: /home/aorfanos/terraform/terraform_0.11.11_linux_amd64.zip
          state: absent

- name: Move executable into $PATH (/usr/bin)
  copy:
          src: "{{ download_path }}/terraform"
          dest: "{{ exec_path }}/terraform"
          remote_src: yes
  become: yes

