---

- name: Install unzip
  apt:
          name: item
          state: present
          with_items:
                  - unzip
  when: ansible_os_family == 'Debian'
  tags: 'prereq'

- name: Install unzip
  yum:
          name: "{{ item }}"
          state: present
  with_items:
          - unzip
  when: ansible_os_family == 'RedHat'
